substitutions:
  device_name: "powmr-inverter"
  node_name: "inverter"
  node_id: powmr_inverter
  inverter_tx_pin: GPIO16
  inverter_rx_pin: GPIO17
  inverter_voltage_offset: "0"
  update_interval: 30s # Minimum 10s recommended to avoid duplicate command errors
  select_skip_updates: "2"

esp32:
  board: esp32doit-devkit-v1

packages:
  main: !include powmr-inverter/main.yaml
  # You can replace next 2 lines with your common configs for all devices
  common_system: !include examples/common_system.yaml
  common_sensors: !include examples/common_sensors.yaml

logger:
  level: WARN
  logs:
    component: ERROR # Fix for issue #4717 "Component xxxxxx took a long time for an operation"

time:
  - platform: homeassistant
    id: hass_time

web_server:
  port: 80
