esphome:
  name: "${node_name}"
  friendly_name: "${node_name}"
  comment: "Monitor and control a SRNE inverter"
  includes:
    - "${device_name}/helpers"
  project:
    name: "odya.esphome-powmr-hybrid-inverter"
    version: 1.3.3
  on_boot:
    priority: -100
    then:
    - delay: 30s
    - lambda: |-
            esphome::modbus_controller::ModbusController *controller = id(smg_inverter);
            setTime(controller);
packages:
  inverter: !include {
    file: modules/inverter.yaml
  }
#  debug: !include modules/debug.yaml

logger:
  level: WARN
  baud_rate: 0
  logs:
    component: ERROR # Fix for issue #4717 "Component xxxxxx took a long time for an operation"
